# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: lms_development
  pool: 5
  username: vincent
  password:

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
